/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Jade Cocoon: Story of the Tamamayu)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x8001047Cu
#define func_8001047C BootEntry  /* alias */
